In [1]:
import pandas as pd
import numpy as np

axis

0 or ‘index’ (for row index / across columns)

1 or ‘columns’ (for column index / across rows)

df -> pd.DataFrame

df[df>0] = -df

df.to_numpy()

df.describe()

df.dtypes

df.T

df.sort_index(axis = 1, ascending = False)

df.sort_values(by = ‘col_label’, axis = 0)

df.isin([’1’, ‘2’])

df.dropna()

df.fillna(values=5)

df.apply(lambda x: x.max()-x.min(), axis = 0)

df.join(other, on=’key’, how, l_suffix, r_suffix)

df.cumsum()

df.cumprod()

df.groupby(‘A’).sum() / min() / max() / count()

pd.concat([df1, df2], join=‘inner’ / ‘outer’)

pd.merge(left, right, left_on=‘lkey’, right_on=‘rkey’)

# Series

In [2]:
s = pd.Series([1,2,3,np.nan,8])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    8.0
dtype: float64

date series

In [3]:
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

# DataFrame

In [4]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns = list('ABCD'))
df

                   A         B         C         D
2013-01-01  0.298875  1.186879 -0.454024  1.449469
2013-01-02  0.564623 -1.248647  0.256777  0.156702
2013-01-03 -0.302038 -0.128308  0.845073  0.026301
2013-01-04 -0.050088 -0.290253  1.452820  0.162205
2013-01-05 -1.413663  1.167655  0.212214 -1.268137
2013-01-06 -0.117293 -0.099575  0.936170 -0.190001

In [5]:
df2 = df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo'})
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [6]:
df

                   A         B         C         D
2013-01-01  0.298875  1.186879 -0.454024  1.449469
2013-01-02  0.564623 -1.248647  0.256777  0.156702
2013-01-03 -0.302038 -0.128308  0.845073  0.026301
2013-01-04 -0.050088 -0.290253  1.452820  0.162205
2013-01-05 -1.413663  1.167655  0.212214 -1.268137
2013-01-06 -0.117293 -0.099575  0.936170 -0.190001

In [7]:
df.apply(lambda row: row.max()-row.min(),axis=1)

2013-01-01    1.903492
2013-01-02    1.813270
2013-01-03    1.147111
2013-01-04    1.743073
2013-01-05    2.581318
2013-01-06    1.126171
Freq: D, dtype: float64

In [8]:
df.apply(lambda col: col.max()-col.min())

A    1.978287
B    2.435525
C    1.906844
D    2.717605
dtype: float64

In [9]:
df3 = pd.DataFrame(np.random.randn(10, 4),columns = list('ABCD'))
df3

          A         B         C         D
0  0.362462  1.498944  0.886558  0.286557
1  0.235774  1.197858 -0.689763  0.228971
2 -0.597445 -0.700386  0.095800  1.989811
3 -1.260733 -0.373449  0.178766 -0.519470
4  0.491481  1.401516 -1.145176 -0.930161
5 -1.735845 -0.134614 -0.113909  0.421113
6  1.239598 -0.590299 -1.423025  0.882727
7 -0.614405  2.041991  0.799520 -0.927791
8  0.910426 -0.448858  0.228625  0.590760
9  0.474727 -0.205905  2.222011  0.741129

In [10]:
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo