https://pub.towardsai.net/manipulating-time-series-data-in-python-49aed42685a0

In [1]:
import pandas as pd
import numpy as np
import datetime as dt

# Axis

1. axis=0, vertically
2. axis=1, horizontally

# datetime.datetime

In [2]:
date = dt.datetime(2017,1,1)
date

datetime.datetime(2017, 1, 1, 0, 0)

In [3]:
date.year, date.month, date.day, date.weekday()

(2017, 1, 1, 6)

# pandas.Timestamp

In [4]:
time_stamp = pd.Timestamp(dt.datetime(2017,1,1))
time_stamp

Timestamp('2017-01-01 00:00:00')

In [5]:
time_stamp.year, time_stamp.month, time_stamp.day, time_stamp.weekday()

(2017, 1, 1, 6)

In [6]:
time_stamp.to_period('D')

Period('2017-01-01', 'D')

# pandas.Period

In [7]:
period = pd.Period('2017-01','D')
period

Period('2017-01-01', 'D')

In [8]:
period = pd.Period('2017-01','B')
period

Period('2017-01-02', 'B')

In [9]:
period = pd.Period('2017-01','W')
period

Period('2016-12-26/2017-01-01', 'W-SUN')

In [10]:
period = pd.Period('2017-01','M')
period

Period('2017-01', 'M')

In [11]:
period = pd.Period('2017-01','Q')
period

Period('2017Q1', 'Q-DEC')

In [12]:
period = pd.Period('2017-01','Y')
period

Period('2017', 'A-DEC')

In [13]:
period.asfreq('D')

Period('2017-12-31', 'D')

In [14]:
period.to_timestamp()

Timestamp('2017-01-01 00:00:00')

In [15]:
period+1

Period('2018', 'A-DEC')

# pandas.date_range

In [16]:
index = pd.date_range(start='2017-1-1', periods=12, freq='M')
index

DatetimeIndex(['2017-01-31', '2017-02-28', '2017-03-31', '2017-04-30',
               '2017-05-31', '2017-06-30', '2017-07-31', '2017-08-31',
               '2017-09-30', '2017-10-31', '2017-11-30', '2017-12-31'],
              dtype='datetime64[ns]', freq='M')

In [17]:
idx_trial = [pd.Timestamp(d).to_period('M') for d in index]
idx_trial

[Period('2017-01', 'M'),
 Period('2017-02', 'M'),
 Period('2017-03', 'M'),
 Period('2017-04', 'M'),
 Period('2017-05', 'M'),
 Period('2017-06', 'M'),
 Period('2017-07', 'M'),
 Period('2017-08', 'M'),
 Period('2017-09', 'M'),
 Period('2017-10', 'M'),
 Period('2017-11', 'M'),
 Period('2017-12', 'M')]

# Upsampling

In [18]:
# Creating Quarterly data
dates = pd.date_range(start='2016', periods=4, freq='Q')
data = range(1, 5)
quarterly = pd.Series(data=data, index=dates)
quarterly

2016-03-31    1
2016-06-30    2
2016-09-30    3
2016-12-31    4
Freq: Q-DEC, dtype: int64

In [19]:
monthly = quarterly.asfreq('M') # to month-end frequency
monthly = monthly.to_frame('baseline') # to DataFrame
monthly

            baseline
2016-03-31       1.0
2016-04-30       NaN
2016-05-31       NaN
2016-06-30       2.0
2016-07-31       NaN
2016-08-31       NaN
2016-09-30       3.0
2016-10-31       NaN
2016-11-30       NaN
2016-12-31       4.0

In [20]:
# Differnet Upsampling fill methods
monthly['ffill'] = quarterly.asfreq('M', method='ffill') # bfill back fill
monthly['bfill'] = quarterly.asfreq('M', method='bfill') # ffill : forward fill
monthly['value'] = quarterly.asfreq('M', fill_value=0)
monthly

            baseline  ffill  bfill  value
2016-03-31       1.0      1      1      1
2016-04-30       NaN      1      2      0
2016-05-31       NaN      1      2      0
2016-06-30       2.0      2      2      2
2016-07-31       NaN      2      3      0
2016-08-31       NaN      2      3      0
2016-09-30       3.0      3      3      3
2016-10-31       NaN      3      4      0
2016-11-30       NaN      3      4      0
2016-12-31       4.0      4      4      4

In [21]:
quarterly.resample('M')
quarterly.asfreq('M').equals(quarterly.resample('M').asfreq())

True

# Rolling Window and Expanding Window

In [22]:
monthly['ffill'].rolling(window=3, min_periods=1).mean()

2016-03-31    1.000000
2016-04-30    1.000000
2016-05-31    1.000000
2016-06-30    1.333333
2016-07-31    1.666667
2016-08-31    2.000000
2016-09-30    2.333333
2016-10-31    2.666667
2016-11-30    3.000000
2016-12-31    3.333333
Freq: M, Name: ffill, dtype: float64

In [23]:
data['running_min'] = data.SP500.expanding().min()
data['running_max'] = data.SP500.expanding().max()
data.plot(figsize=(10,10))

AttributeError: 'range' object has no attribute 'SP500'

In [ ]:
df.rolling(window=252).mean()
df.expanding().min()

# Join, Concat, Merge

1. merge() for combining data on common columns or indices
2. join() for combining data on a key column or an index
3. concat() for combining DataFrames across rows or columns

In [24]:
df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3', 'K4', 'K5'],
                   'A': ['A0', 'A1', 'A2', 'A3', 'A4', 'A5']})
df1

  key   A
0  K0  A0
1  K1  A1
2  K2  A2
3  K3  A3
4  K4  A4
5  K5  A5

In [25]:
df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                      'B': ['B0', 'B1', 'B2']})
df2

  key   B
0  K0  B0
1  K1  B1
2  K2  B2

- module function
- You can use merge() anytime you want functionality similar to a database’s join operations
- When you want to combine data objects based on one or more keys, similar to what you’d do in a relational database, merge() is the tool you need. More specifically, merge() is most useful when you want to combine rows that share data.

In [26]:
df_total = pd.merge(
    df1,
    df2,
    how='left', #outer/left/right
    on=['key'],
    #left_on=['key1','key2'],
    #right_on=['key1','key2'],
)
df_total

  key   A    B
0  K0  A0   B0
1  K1  A1   B1
2  K2  A2   B2
3  K3  A3  NaN
4  K4  A4  NaN
5  K5  A5  NaN

- a class method of pd.DataFrame
- join() is an instance method that lives on pd.DataFrame
- if key not specified, join by common column
- if key specified, join by key

In [27]:
df1.join(df2,lsuffix='_caller', rsuffix='_other')

  key_caller   A key_other    B
0         K0  A0        K0   B0
1         K1  A1        K1   B1
2         K2  A2        K2   B2
3         K3  A3       NaN  NaN
4         K4  A4       NaN  NaN
5         K5  A5       NaN  NaN

In [28]:
df1.set_index('key').join(df2.set_index('key'))

      A    B
key
K0   A0   B0
K1   A1   B1
K2   A2   B2
K3   A3  NaN
K4   A4  NaN
K5   A5  NaN

In [29]:
df1.join(df2.set_index('key'), on='key')

  key   A    B
0  K0  A0   B0
1  K1  A1   B1
2  K2  A2   B2
3  K3  A3  NaN
4  K4  A4  NaN
5  K5  A5  NaN

- with concatenation, your datasets are just stacked together along an axis

In [30]:
pd.concat([df1,df2])

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

     A    B key
0   A0  NaN  K0
1   A1  NaN  K1
2   A2  NaN  K2
3   A3  NaN  K3
4   A4  NaN  K4
5   A5  NaN  K5
0  NaN   B0  K0
1  NaN   B1  K1
2  NaN   B2  K2

In [31]:
df3 = pd.DataFrame([['a', 1], ['b', 2]],
                   columns=['letter', 'number'])
df3

  letter  number
0      a       1
1      b       2

In [32]:
df4 = pd.DataFrame([['c', 3], ['d', 4]],
                   columns=['letter', 'number'])
df4

  letter  number
0      c       3
1      d       4

In [33]:
pd.concat([df3,df4]) #vertically

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [34]:
pd.concat([df3,df4],axis=1) #horizontally

  letter  number letter  number
0      a       1      c       3
1      b       2      d       4

In [35]:
df5 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
                   columns=['letter', 'number', 'animal'])
df5

  letter  number animal
0      c       3    cat
1      d       4    dog

In [36]:
pd.concat([df3, df5], sort=False)

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

In [37]:
pd.concat([df3, df5], join='inner')

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [38]:
pd.concat([df3, df5], join='outer')

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

  animal letter  number
0    NaN      a       1
1    NaN      b       2
0    cat      c       3
1    dog      d       4

In [41]:
df5['test'] = df5['number'].apply(lambda r: r>3)
df5

  letter  number animal   test
0      c       3    cat  False
1      d       4    dog   True